### ISSUE TITLE
Add full workflow of use case example

### ISSUE THREAD

**Issue by paigem** [rcaneill/xnemogcm#96]
**Feature request:** It would be helpful for users to see a full workflow of using `xnemogcm`, and seeing how it fits together with `xgcm` and how that can be used for analysis.

This is a suggested feature request, but is not one that will hold up my review. 🙂

One of the primary motivations listed for why `xnemogcm` is a useful package is that it can be used in conjunction with `xgcm`. At the moment, the only example of using `xnemogcm` with `xgcm` is in the very short "Usage" text in the README. This "Usage" text is great, but I think it would be even more helpful to have a more complete use case example that (for instance) opens up some NEMO data, uses `xnemogcm` and then uses `xgcm` to do some sort of standard ocean analysis, ideally resulting in a nice plot. Specifically, it would be nice to have a script that can be run locally, e.g. with a small subset of NEMO data (the "Usage" section as it stands cannot be run unless the user already has access to NEMO data) that demonstrates a full sample workflow.

**Comment by rcaneill** [comment]
I wrote an example in the xgcm documentation for NEMO: https://xgcm.readthedocs.io/en/latest/xgcm-examples/04_nemo_idealized.html
Thus, I do not think that it would be necessary to redo it in the xnemogcm doc. However, I should add the link the the xgcm doc.

(I updated the xgcm example, but it is not merged yet)

**Comment by rcaneill** [comment]
(I let you reopen this issue if you think that more work would be needed)
